### ISSUE TITLE
Contribution modal shows up for a second on Firefox

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#100]

**Comment by Mesoptier** [comment]
We could just implement this feature already :stuck_out_tongue: Alternatively we can add `display: none` on the modal for now.

**Comment by villermen** [comment]
Happens for all modals, and even on Chrome on first page load. (But not after due to some rendering optimizations I'd assume.)

It happens because the `modal` class has
```
    transition: opacity 200ms ease, visibility 200ms ease;
    transform: rotate3d(0,0,0,0deg);
```

Which gives it a nice closing animation, but the animation also plays when the modal is first rendered.

The best way I can think of to stop this from happening is having a `.modal--hidden` class that is added by closing the modal, but is absent when first loaded.
