### ISSUE TITLE
Scroll to sample not working in Firefox

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#102]
No error shown in console, it just doesn't do anything when using an url with a sample's hash in it.

**Comment by villermen** [comment]
Mesoptier:

> Tried Googling this, surely StackOverflow knows something?

**Comment by Mesoptier** [comment]
This could simply be an issue of `<body>` vs `<html>`, as I think Chrome and Firefox use a different one for scrolling the window.

So it might be a case of changing `body` to `html, body` on this line: https://github.com/villermen/soundboard/blob/master/src/client/scripts/components/SampleContainer.js#L165
