### ISSUE TITLE
Split frontend and backend projects

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#105]
Separation of concerns and dependencies.

**Comment by villermen** [comment]
Group it under an organization? With what name?

**Comment by Mesoptier** [comment]
But why should the frontend and backend not be tightly coupled?

**Comment by villermen** [comment]
E.g. I've configured to use the live backend when developing the frontend. And there's also [spamboard.nl](http://spamboard.nl), which has the full package checked out but only uses the frontend too.
