### ISSUE TITLE
Add ability to chain multiple samples

### ISSUE THREAD

**Issue by cascer1** [team-thyme/soundboard#112]
Clicking samples in order is a pain for us mere mortals. Instead, allow us to queue multiple sounds so they play in order.

**Comment by villermen** [comment]
Functionality included in #86.

**Comment by cascer1** [comment]
I must be missing some rewrite rules then

![I must be missing some rewrite rules then](https://ducohosting.com/screenshots/deskc920bd7cd2b15caffaa75e39b863f796.png)
