### ISSUE TITLE
Slow search

### ISSUE THREAD

**Issue by stackErr-NameNotResolved** [team-thyme/soundboard#115]
Slow search performance on Elephone p9000. Chrome browser on Android hangs. 

Search performance on quick laptop is not snappy.

**Comment by villermen** [comment]
Does [this](https://viller.men/soundboard) perform better?

**Comment by villermen** [comment]
Then again this might be our old enemy the flexbox as well...

**Comment by Mesoptier** [comment]
Yeah, this is gonna be on Flexbox again. The browser is just having a hard time recalculating all those variable width boxes. 😢 

We could try virtualizing (so all elements off-screen aren't rendered). <sup><sub>Or rendering to canvas....</sub></sup>

**Comment by stackErr-NameNotResolved** [comment]
Well it sure behaves different. Not really better though. Chrome on Android does not seem to hang anymore, which is a nice improvement! However the large debounce delay on pc yields results slower. So... debounce on mobile and no debounce on desktop?

**Comment by villermen** [comment]
https://github.com/bvaughn/react-virtualized
