### ISSUE TITLE
Do sample sorting in JavaScript

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#12]
Used to be done with PHP:

```
    usort($samples, function ($sample1, $sample2) {
      if ($sample1->mtime > $this->sortLimit || $sample2->mtime > $this->sortLimit) {
        return $sample2->mtime - $sample1->mtime;
      }

      return 2 * mt_rand(0, 1) - 1;
    });
```

**Comment by Mesoptier** [comment]
What's the advantage doing this in JS?

**Comment by villermen** [comment]
It's visual stuff, so the backend should not come into play for it. I am lazy and reply to multiple issues at the same time #13. I can implement this though.

**Comment by villermen** [comment]
https://github.com/Villermen/soundboard/commit/9197cc6151636f87df191586723b22e853e3c706
