### ISSUE TITLE
Create separate install script/task

### ISSUE THREAD

**Issue by Mesoptier** [team-thyme/soundboard#16]
Instead of putting everything in `postinstall`, which is really just for NPM. Especially `composer install` in `postinstall` is nasty.

This could be an NPM script (not `postinstall`), a gulp task, or something else entirely.

**Comment by villermen** [comment]
Added in https://github.com/Villermen/soundboard/commit/f770bb85ab01864c84cf0d8a1f9566730cd54af8.
