### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#25]
![Failed to decode downloaded font](http://puu.sh/pigkM/bddca994e8.png)

Not sure if already solved, so here ya go.

**Comment by Mesoptier** [comment]
Probably an issue with `.htaccess`?

**Comment by villermen** [comment]
When I follow the urls the files are alright though. I'll try to check what's causing it.

**Comment by villermen** [comment]
> jodamo5
> 
> # MARCH 8, 2016 AT 6:36 PM
> 
> I just had the same issue – but with Font Awesome, which is a really well known font. Turned out this was caused by a problem with FTP. The file was uploaded as text (ASCII) instead of binary, which corrupted the file. I simply changed my FTP software to binary, re-uploaded the font files, and then it all worked.

**Comment by villermen** [comment]
Making the server respond with the correct Content-Type also did not resolve the issue. ~~Could you try cloning the repository fresh, and see if git has maybe changed the encoding of the file?~~ The files are built ourselves so that wouldn't make sense either.

**Comment by villermen** [comment]
Downloading the file from its original repository and uploading it to the public directory makes it work, so there must be something wrong with the files themselves. Having it in the source and making gulp clean and build it also doesn't corrupt it, so if it works for you it must have something to do with git.

**Comment by villermen** [comment]
Gotcha: ![Silly git](http://puu.sh/piRnq/7be5a62e39.png)

**Comment by Mesoptier** [comment]
Maybe we can mark the font files as binary in `.gitattributes`? See: https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#Binary-Files

**Comment by villermen** [comment]
Done (6c2ba9357b4839183ba36cb5e4b8dc1f6b0752fd), now I just need to check if re-cloning on production fixes it.

**Comment by Mesoptier** [comment]
btdoubleu, I was planning to move to a CDN-hosted iconfont :innocent:

**Comment by villermen** [comment]
Not a reason to skip out on experiencing how git can also NOT work. But 2 commits later we have the bytes:

![Ladies and gentlemen, we've got them](http://puu.sh/piT3p/9df73036b8.png).

**Comment by villermen** [comment]
1c1db41cbfd20c7b2e2dfa36629b331b27206076
