### ISSUE TITLE
Spamclicking one sample with shift

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#31]
It will not cut out even when shift is held.

**Comment by Mesoptier** [comment]
When spam-clicking with <kbd>Shift</kbd> pressed, it was my intention that it kept resetting. Is that not desired behaviour?

**Comment by villermen** [comment]
No, that's what it's supposed to do when not holding anything. With <kbd>shift</kbd> pressed all hell should break loose, like on the current soundboard.

**Comment by villermen** [comment]
Added in 8ebba7feb30b7853e7ca726f2e070f1531b15de2.
