### ISSUE TITLE
Instructions, somewhere...

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#38]
Because people need to know how to spam the most.

**Comment by Mesoptier** [comment]
I'm probably just going to add a section in the settings modal for this.

**Comment by villermen** [comment]
Bullet list of things it should contain (edit where needed):
- <kbd>Enter</kbd> in search bar to play random
- Hold <kbd>Shift</kbd> to play multiple samples
- Hold <kbd>Ctrl</kbd> to play on a loop
- Right-click on a sample to stop it
- <kbd>Space</kbd> when not in search bar to stop all audio

**Comment by Mesoptier** [comment]
Continued in https://github.com/villermen/soundboard/issues/84.
