### ISSUE TITLE
Stop all

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#39]
Because when I loop/spam a lot, I want to be able to stop everything at once.

Maybe with <kbd>space</kbd>?

**Comment by Mesoptier** [comment]
<kbd>Space</kbd> is already assigned to playing a random sample. But maybe just <kbd>Enter</kbd> in the search bar is enough.

BTW, <kbd>Shift</kbd> and <kbd>Ctrl</kbd> work with both those keys.

**Comment by villermen** [comment]
Thar, 3fb7b9e71931c75943212438ecacbee5bdadfa2a.
