### ISSUE TITLE
Allow for slashes in soundboard url argument

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#41]
It didn't quite work with `<base href="/" />`, so we're having our future selves deal with it.

**Comment by Mesoptier** [comment]
As per https://xkcd.com/1421/

**Comment by villermen** [comment]
Cheesed it in 22cb2adb0d7f19b6eb7e486e927497ef465ed289.

**Comment by Mesoptier** [comment]
This could be easily solved if the config files were not in version control. We can have client.default.yml & server.default.yml in git, and client.yml & server.yml out of it. Then we can just add a `baseUrl` option to server.yml and set the `<base>` tag from that.

**Comment by villermen** [comment]
Current solution as of https://github.com/team-thyme/soundboard-front-end/commit/6b1523800cbc7274bddfcf7a843504a524bc9687#diff-528c3923d718a8860f5d8c05c3931c55R7 is to have a base tag that needs to be manually changed if a subdirectory is used. I know no better way of doing this at this time.

**Comment by Mesoptier** [comment]
@villermen I think this is solved with the BASE_URL env variable these days, right?

**Comment by villermen** [comment]
Right you are! This was already fixed in #138.
