### ISSUE TITLE
Scroll to random sample on Enter

### ISSUE THREAD

**Issue by Mesoptier** [team-thyme/soundboard#50]

**Comment by villermen** [comment]
Please review if a0f45bcc4700ec510dc160c651382c8631d0157b and 2e5f0e9f1f0cfe36f475960cb34cdfe541b39774 implement this in a [satisfactory fashion](https://viller.men/soundboard/05bf20fe).

**Comment by Mesoptier** [comment]
[Ja, man.](https://viller.men/soundboard/f3bd8f52)
