### ISSUE TITLE
Configuration file for frontend

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#6]
E.g. for google doc id.

**Comment by villermen** [comment]
One config file (config/config.json) for both ends, or one per end (config/client.json, config/server.yaml)? @Mesoptier

**Comment by Mesoptier** [comment]
JSON for the client would be better, since IDEs can do some code intelligence on those.

**Comment by villermen** [comment]
NO, YAML! ***stamps on ground with overwhelming confidence***
