### ISSUE TITLE
We need to take our lovely japanese intern out back

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#61]
She should resume her English training soon, otherwise she will never be accepted as our receptionist.

**Comment by villermen** [comment]
Nobody saw the typo.

**Comment by Mesoptier** [comment]
What?

**Comment by villermen** [comment]
She wouldn't like it there.

**Comment by villermen** [comment]
06ee4aa1b04e1d8088a80b1d5fd2ce7bebd4e46a
