### ISSUE TITLE
New theme color specification

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#62]
For applying colors in other places, I was thinking of making the color names more generic:
- headers-background and text (headers and buttons)
- input-background and text (search and modal body)
- body-background, accent and text (for sample container and samples, where sample backgrounds would be accent)
- footer-background and text (or maybe this could be just the header and input mixed)

**Comment by villermen** [comment]
:ok:?

**Comment by Mesoptier** [comment]
But this is completely ungeneric.. Using `input-background` for a modal body? This is how I originally had the variables, but I decided to use more abstract color names instead so it would be easier to extend later on.

**Comment by villermen** [comment]
I started the issue with:
primary-background and text, secondary-background and text, tertiary-background and text, etc. I can't remember why I switched over mid-way through but this is what I wanted to put there. :confused:

**Comment by Mesoptier** [comment]
Right now I have `primary` and `primary-text` which are basically already `primary-background` and `text-on-primary-background`.
