### ISSUE TITLE
Automatically focus search box

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#64]
autofocus =)

**Comment by villermen** [comment]
Autofocus alone (a6ae35cb456ec26e534b013b99c45d29de6df97c) did not fully fix it. Something removes focus, most likely some JavaScript load thing.

**Comment by Mesoptier** [comment]
Probably because of the `<body>` being detached and re-attached in `ThemeManager`. I'm already getting rid of it while working on the modal-flashing bug.

**Comment by Mesoptier** [comment]
Works fine now because of 8c186ff5f18c4bce40172d1ffde04df692a2b68f.
