### ISSUE TITLE
ctrl+shift+enter on search bar no longer does the loop spams

### ISSUE THREAD

**Issue by cascer1** [team-thyme/soundboard#65]
Does work on clicks still

**Comment by villermen** [comment]
Fixed in d500f02b8b99d827e71e2fa9a317880c8c4c02d0.

**Comment by cascer1** [comment]
Als je nou in de commit message `close #65` doet, hoef je hem niet apart te closen :smile: 

#GitHubPro

**Comment by villermen** [comment]
Ja, zodra hij in master gemerged wordt ja. Meneer #GitHubPro #HumbleBragButActuallyNot
