### ISSUE TITLE
Remove sample id from URL on stop?

### ISSUE THREAD

**Issue by Mesoptier** [team-thyme/soundboard#76]
Because I am often testing the soundboard by playing/stopping samples and refreshing the page, and it is frustrating when it keeps restarting the samples after a refresh.

Under some conditions of course:
- When the user initiates the stop (right click on desktop or long press on mobile). So **not** when the sample ends or another sample is started.
- Only if the id of the stopped sample equals that in the URL.
- I would keep it in the history, so `pushState` instead of `replaceState`.

**Comment by villermen** [comment]
Yes, but also on <kbd>Space</kbd>.
8/10.

**Comment by Mesoptier** [comment]
What do we do when you have stopped a sample and `""` was pushStated and then either:
1. Press another sample, will the history be `"sample-1" > "" > "sample-2` or `"sample-1" > "sample-2"`?
2. Press the same sample, will the history be `"sample" > "" > "sample"`, `"sample" > "sample"` or `"sample"`?

**Comment by villermen** [comment]
Ideally I'd say `"" > "sample-1" > "sample-2"` and `"" > "sample"`. But note that the first empty state should still be there, so it might be hard to implement that. If it was not for the first empty state, we could just replaceState whenever the current one is empty.
