### ISSUE TITLE
Modal instantly appears and fades out when reloading soundboard

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#78]
Not on load, my mistake.

![see?](http://puu.sh/pB92K/253d766be7.png)

**Comment by Mesoptier** [comment]
I'm getting it too, dammit.

**Comment by villermen** [comment]
Temporary fix, that also prevents the fade out animation from happening legitly, in 1f9c1e70255c51a93761739ccade4150f6b4616a.

**Comment by Mesoptier** [comment]
Yeah, that's been my fix so far as well. I just cannot figure out what is causing this, and it's occurring sporadiously so it's hard to debug. :disappointed:

**Comment by Mesoptier** [comment]
I think I found the cause for this issue. For some reason when our fonts are loaded using `@import`, Chrome does some weird re-rendering when they have loaded. I think I have solved it by moving them to `<link>` tags. (b11d99936c271caf0d4174a4b239bb39b04f8c6b)
