### ISSUE TITLE
Looping no longer works

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#79]
Probably due to HTML5 audio :cry:.

**Comment by Mesoptier** [comment]
I've figured out what is causing this. Howler fires `stop` when it reaches the end of a sound, regardless of whether it's looping. We then pick up this event and remove the index from the `playing` array. Howler then starts the sample again and fires a `play` event, but as the index is no longer in the `playing` array, we immediately stop it again.

![log](http://i.imgur.com/qnv7zZr.png)

I don't think a `stop` event should be fired at the end of a loop, so I'll create an issue with Howler.

**Comment by Mesoptier** [comment]
https://github.com/goldfire/howler.js/issues/549

**Comment by villermen** [comment]
This guy gets a thumbs up.

**Comment by Mesoptier** [comment]
Temporary fix in ee1e3c07fe8b65f6dfe83438560b7ae98e525dea. I only actually stop a sample when it's `loop` property is false. This would mean that looping samples cannot be stopped, so when a user manually stops a sample, the `loop` property will be set to false.

**Comment by villermen** [comment]
Reopened because otherwise we will forget about it.

**Comment by villermen** [comment]
2eac77d6624fce1d70969726b26578508ff38a7f :tada:
