### ISSUE TITLE
Simplicity does not work in HTML5

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#80]
I removed tags, saved again. There is something very wrong with the file, but what?

Works in Firefox, not in Chrome...

**Comment by Mesoptier** [comment]
What tags and what file?

**Comment by villermen** [comment]
https://viller.men/soundboard/api/samples/music/macroform/simplicity.ogg

**Comment by Mesoptier** [comment]
It does work when I download the file and open it in Chrome again. So there is something wrong with the delivery of the server.

I think the best thing we can do to avoid issues like this is to stop delivering the files through a PHP script using `readfile()`. It's probably better to directly link to the files and have Apache [deel vit it](https://viller.men/soundboard/d4c4111f). This is the way most API's work anyway, they give a direct link to a file.

**Comment by villermen** [comment]
Then we should probably symlink /public/api/samples to /samples

**Comment by Mesoptier** [comment]
Well, I'd say the files aren't part of the API, so they shouldn't be under `public/api`. Instead I'd symlink/htaccessify `public/samples` or `public/files` to the samples directory.

**Comment by villermen** [comment]
Fair 'nuf.

**Comment by villermen** [comment]
Fixed in 53eab311f3d32388b65351433888685bee4ad60b.

I did not use a symlink because that requires adminstrator rights, and I couldn't make .htaccess work because of the public directory being symlinked. I went with a PHP router instead.
