### ISSUE TITLE
Round volume value

### ISSUE THREAD

**Issue by villermen** [team-thyme/soundboard#81]
Because of 

![this](http://puu.sh/pBOmn/9378168e82.png)

**Comment by Mesoptier** [comment]
Huh? I am directly taking the value from the input, how does that get messed up? But yeah, rounding before displaying should work :P

**Comment by villermen** [comment]
Fixed in 13fcfdb6d88ff11277c7c4fb939127bbb14d907d.

**Comment by Mesoptier** [comment]
I just fixed this locally! :joy: We need to assign issues..

**Comment by villermen** [comment]
Whey!
