### ISSUE TITLE
Controls modal

### ISSUE THREAD

**Issue by Mesoptier** [team-thyme/soundboard#84]
I'm thinking about adding this as a tab in the settings modal. But before doing so, I think we need a complete list of controls. And we also need to think about future controls/keys.

<hr>
- \* <kbd>Left-click</kbd> Play sample
- <kbd>Right-click</kbd> Stop sample
- <kbd>Space</kbd> Stop all samples
- \* <kbd>Enter</kbd> (in search) Play random sample from results

Controls marked with a \* can be used with the following modifier keys:
- <kbd>Shift</kbd> Play multiple samples
- <kbd>Ctrl</kbd> Loop sample

<hr>

@villermen, did I miss anything?

**Comment by Mesoptier** [comment]
Oops, duplicate of https://github.com/villermen/soundboard/issues/38. Let's continue in this issue though.

**Comment by villermen** [comment]
> @villermen, did I miss anything?

@Mesoptier, No.

**Comment by Mesoptier** [comment]
Not so, he!

**Comment by villermen** [comment]
Context menu shows controls too. Still needed?
