### ISSUE TITLE
Playback on mobile cuts off too early

### ISSUE THREAD

**Issue by cascer1** [team-thyme/soundboard#87]
Android N DP 4 on Nexus 6P

It cuts off about .5 seconds early every time.

**Comment by villermen** [comment]
You forgot to plug your cutting edge browser too.

**Comment by cascer1** [comment]
**Google Chrome**
51.0.2704.90 (Official Build) (32-bit)
**Revision**
ffa91cd0bc7da1f2d9c08393a903ef4471ca1954-refs/branch-heads/2704_81@{`#4`}
**OS**
Android 6.0.99; Nexus 6P Build/NPD56N
**Blink**
537.36 (`@ffa91cd0bc7da1f2d9c08393a903ef4471ca1954`)
**JavaScript**
V8 5.1.281.59
**User Agent**
Mozilla/5.0 (Linux; Android 6.0.99; Nexus 6P Build/NPD56N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.90 Mobile Safari/537.36

**Comment by villermen** [comment]
It seems like this is another howler bug. I'll need to be sure before I submit an issue there though, so I'll need to investigate first.

**Comment by villermen** [comment]
It magically fixed itself, so it was probably a Chrome bug. Can @anyone confirm?
